app = "task-master-4jz3va"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  ASPNETCORE_ENVIRONMENT = "Production"
  # Persist SQLite on the mounted volume:
  ConnectionStrings__Default = "Data Source=/data/taskmaster.db"

[http_service]
  internal_port = 8080
  force_https = true

  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 10
    hard_limit = 20

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "15s"
    method = "GET"
    path = "/health"

[[mounts]]
  source = "data"
  destination = "/data"
